CREATE OR REPLACE TABLE DEV_DB_TESTING.SCH_BR_LAYER.TBL_TEST11(
Customer_ID INT,Age INT,Gender VARCHAR(20),Item_Purchased VARCHAR(20),Category VARCHAR(30),Purchase_Amount_USD INT,Location VARCHAR(30),Size VARCHAR(30),Color VARCHAR(30),Season VARCHAR(30),Review_Rating FLOAT,Subscription_Status VARCHAR(10),
Shipping_Type VARCHAR(30),Discount_Applied VARCHAR(30),Promo_Code_Used VARCHAR(30),Previous_Purchases INT,Payment_Method VARCHAR(30),Frequency_of_Purchases VARCHAR(40))
;


--INSERTING THE DATA 
INSERT INTO DEV_DB_TESTING.SCH_BR_LAYER.TBL_TEST11 VALUES(
 (1, 55, 'Male', 'Blouse', 'Clothing', 53, 'Kentucky', 'L', 'Gray', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 'Yes', 14, 'Venmo', 'Fortnightly'),
(2, 19, 'Male', 'Sweater', 'Clothing', 64, 'Maine', 'L', 'Maroon', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 'Yes', 2, 'Cash', 'Fortnightly'),
(3, 50, 'Male', 'Jeans', 'Clothing', 73, 'Massachusetts', 'S', 'Maroon', 'Spring', 3.1, 'Yes', 'Free Shipping', 'Yes', 'Yes', 23, 'Credit Card', 'Weekly'),
(4, 21, 'Male', 'Sandals', 'Footwear', 90, 'Rhode Island', 'M', 'Maroon', 'Spring', 3.5, 'Yes', 'Next Day Air', 'Yes', 'Yes', 49, 'PayPal', 'Weekly'),
(5, 45, 'Male', 'Blouse', 'Clothing', 49, 'Oregon', 'M', 'Turquoise', 'Spring', 2.7, 'Yes', 'Free Shipping', 'Yes', 'Yes', 31, 'PayPal', 'Annually'),
(6, 46, 'Male', 'Sneakers', 'Footwear', 20, 'Wyoming', 'M', 'White', 'Summer', 2.9, 'Yes', 'Standard', 'Yes', 'Yes', 14, 'Venmo', 'Weekly'), 
(7, 63, 'Male', 'Shirt', 'Clothing', 85, 'Montana', 'M', 'Gray', 'Fall', 3.2, 'Yes', 'Free Shipping', 'Yes', 'Yes', 49, 'Cash', 'Quarterly'),
(8, 27, 'Male', 'Shorts', 'Clothing', 34, 'Louisiana', 'L', 'Charcoal', 'Winter', 3.2, 'Yes', 'Free Shipping', 'Yes', 'Yes', 19, 'Credit Card', 'Weekly'),
(9, 26, 'Male', 'Coat', 'Outerwear', 97, 'West Virginia', 'L', 'Silver', 'Summer', 2.6, 'Yes', 'Express', 'Yes', 'Yes', 8, 'Venmo', 'Annually'),
(10, 57, 'Male', 'Handbag', 'Accessories', 31, 'Missouri', 'M', 'Pink', 'Spring', 4.8, 'Yes', '2-Day Shipping', 'Yes', 'Yes', 4, 'Cash', 'Quarterly'));

--RETRIVING THE DATA 
select * from DEV_DB_TESTING.SCH_BR_LAYER.TBL_TEST11;